### ISSUE TITLE
Support for Sponge

### ISSUE THREAD

**Issue by TheAwesomeGem** [Microsoft/vsminecraft#5]
Will this extension support Sponge in the future? Sponge is basically a server API for Forge and other implementations.

https://spongepowered.org/

**Comment by me4502** [comment]
Yeah, this would be useful.

**Comment by mluparu** [comment]
I took a look at what it would take to support Sponge. Since it has a Maven repo, it can be added to your project's build.gradle following the instructions on Sponge's page [Adding Sponge API Dependencies](https://docs.spongepowered.org/en/plugin/basics/workspace/dependencies.html)

Here's what you need to do next: 
- After you change build.gradle, start a build in VS. The change in build.gradle will be detected and a provisioning build will start.
- When the build is done, you need to manually update the project references in Solution Explorer:
  (1) select all references from the "References" node, delete them and save your project
  (2) reprovision your project by following the instructions in Hello.txt (i.e. execute the DTE command CustomCommands.ProvisionMinecraftProject).

That's it. After this, you should be able to start using the types from Sponge. 
![untitled](https://cloud.githubusercontent.com/assets/12057413/7446839/7567a27c-f19a-11e4-9cc7-cec63ee79697.png)

Let me know if it works for you.

**Comment by mluparu** [comment]
I created #7 and #8 to improve this workflow

**Comment by TheAwesomeGem** [comment]
Did not seem to work for me. I did the exact steps and the Sponge is neither on the reference nor I can access or import it.

**Comment by mluparu** [comment]
Do you see any references of sponge libs in the .classpath file at the root of your projects though?

**Comment by TheAwesomeGem** [comment]
Yes it is:

"<classpathentry kind="lib" path="E:/ForgeMods/TestMod/TestMod/unresolved dependency - org.spongepowered spongeapi 2.0" exported="true"/>"

**Comment by mluparu** [comment]
Weird. If .classpath has them, you should at least see them in Intellisense autocomplete operations (like the screenshot I added). Can you check whether the path to the .jar file that .classpath points to actually exists on disk? Maybe also try to close all java editors in VS and open them again to restart the Eclipse backend.
